### PR TITLE
Related entities

### PR DESCRIPTION
**Pull request by zquintana**
Added related entities support via adding getter name property to the Field annotation. So adding the related entity is as simple as:

```php
    /**
     * @var ArrayCollection
     *
     * @Solr\Field(type="strings", getter="getName")
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="post")
     * @ORM\JoinTable("posts_tags")
     */
    private $tags;
```

### CODE REVIEW

**Comment by floriansemm** [comment]
:+1: 

I will review/test it later today

**Comment by floriansemm** [comment]
I have test your pull-request a bit and I found some points:
- add test for the feature
- I got an exception on inversed-side: `Error: Call to a member function getTitle() on null, FS/SolrBundle/Doctrine/Mapper/Mapping/MapAllFieldsCommand.php at line 46`. In your case it would be `$tag->getPost()`

My config:
Post
```php
    /**
     * @var Category
     *
     * @Solr\Field(type="string", getter="getTitle")
     * @ORM\ManyToOne(targetEntity="Acme\DemoBundle\Entity\Category", inversedBy="posts")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;
```
Category
```php
    /**
     * @var Post[]
     *
     * @Solr\Field(type="strings", getter="getTitle")
     * @ORM\OneToMany(targetEntity="Acme\DemoBundle\Entity\Post", mappedBy="category")
     */
    private $posts;
```

**Comment by zquintana** [comment]
Looks like the problem was that I didn't have logic in place to make sure the entity was in place. Fix it now. In my latest patch.

**Comment by zquintana** [comment]
Just realized the this branch I pushed, by accident fixes for the newest solarium versions. I can remove that if need be. Let me know.

**Comment by surivrox** [comment]
Any update on this?

**Comment by floriansemm** [comment]
I am working on this "relation-problem", based on this pull-request

**Comment by zquintana** [comment]
Sorry guys. Here's the update. Problem is that I've added a few more features into my branch. I added VirtualFields properties and fixed an issue with the doctrine hydrator that would query n amount of records from the database during hydration. Switched that to a find all so it would be one query rather then n.  I also added a basic DataCollector so that you can see the actual queries being passed to Solr. Problem is that all of that is on my dev branch. @floriansemm how would you like me to arrange this for you to pull in?

**Comment by floriansemm** [comment]
@zquintana you can create another pull-request for your new features or attach them to this pull-request. Then I will merge your changes into the `zquintana-related_entities` branch which contains all the related-entities stuff.

**Pull request merged**
